### ISSUE TITLE
Add to hackage

### ISSUE THREAD

**Issue by bsima** [frontrowed/sendgrid#5]
This seems to be the best sendgrid client library available. Would be nice to have it on hackage. Currently I just write my own nix expression for it or add to stack.yaml (depending on which tooling I'm using).

**Comment by eborden** [comment]
Hey @bsima we actually no longer use this library. We had planned to "archive" it, but hadn't gotten around to it. We have an internal library that is much simpler and uses more modern sendgrid APIs. We'll hopefully take the time to get that open sourced.

**Comment by bsima** [comment]
Oh, well I guess my afternoon will be spent switching to this one perhaps https://hackage.haskell.org/package/sendgrid-v3
